### ISSUE TITLE
这个锁用的有问题吧

### ISSUE THREAD

**Issue by charliexp** [DrmagicE/gmqtt#155] opened 2022-01-14 08:48 UTC
![image](https://user-images.githubusercontent.com/12693198/149485930-2143a4f6-6126-4b80-83e6-95ceda864e9a.png)

**Comment by charliexp** [comment] 2022-01-14 08:50
还有MQTT5中共享订阅，数据会重复推送，就是每个客户端会接收到两个相同的消息，而且没有起到共享订阅的功能

**Comment by DrmagicE** [comment] 2022-01-14 09:47
The code snippet you pointed out here is a little tricky. The purpose of the `lockDuplicatedID` is to ensure the uniqueness of the clientID, which is demanded by the MQTT protocol.  

Specifically, the method does the following:
Check if there is already has a session with the same clientID in the broker. 
If yes, then close the session and check again.
if no, then lock the `srv. mu` mutex and break the `for` loop to continue the rest of client registration process in `registerClient`.

Because of the uniqueness requirement of the client id, the broker must register the clients one by one, which means the client registration process is synchronous and should be guarded by the `srv.mu` mutex.  When `lockDuplicatedID` returns, the `srv.mu` will be locked, and it will be unlocked once the registration process is done.

**Comment by DrmagicE** [comment] 2022-01-14 10:00
@charliexp Could you please provide more details about how to reproduce the problem? I just check it and it works fine.

It is worth noting that gmqtt only support random strategy for the message distribution of share subscription. When using share subscription, messages may send to the same subscriber continually, but should not send copies to both of them at the same time.

**Comment by charliexp** [comment] 2022-01-14 10:30
关于锁我看明白了，在两个函数中，但我遇到一个问题是，服务器启动后，有一个客户端连接并push比较大的数据后，ctrl+c终止它，多试几次就卡住，此时再连客户端会有“”logging with duplicate ClientID“”提示，主要是因为上一次连接没法close
![image](https://user-images.githubusercontent.com/12693198/149500492-5cfc107f-20e6-4a47-af31-a444114b7081.png)

![image](https://user-images.githubusercontent.com/12693198/149500994-be88042c-0f09-438d-aaaa-383a66b09528.png)

**Comment by charliexp** [comment] 2022-01-14 10:36
关于共享订阅很容易试出来，基本是百分百，我的环境是Ubuntu 18.04 64bit 在台机器模拟开三个节点的集群，一个客户端push，两个共享订阅端订阅同一个topic。三个客户端分别连不同的节点。
三个节点的mqtt port 分别是1883 1884 1885

**Comment by DrmagicE** [comment] 2022-01-14 10:38
It is ok. As the logs say, the related session is reused by your new client. The connection of the old client will be closed by the broker.

**Comment by DrmagicE** [comment] 2022-01-14 10:40
> 关于共享订阅很容易试出来，基本是百分百，我的环境是Ubuntu 18.04 64bit 在台机器模拟开三个节点的集群，一个客户端push，两个共享订阅端订阅同一个topic。三个客户端分别连不同的节点。 三个节点的mqtt port 分别是1883 1884 1885

What’s your complete subscription topic and publish topic?

**Comment by charliexp** [comment] 2022-01-14 10:52
旧客户端的连接关闭不了，整个服务器必须要kill -9才能关闭！这样会造成有指定的clientid的客户端没法连接。
刚才复现一下共享订阅的问题，复现不出来了，比较奇怪，我订阅的topic很简单：
共享订阅：$share/mq/a/b/#
push ：client.publish( 'a/b/'+i, 'test'+i , {qos:1,retain: false} ); 不过这个数量比较多，一次发送10万个数据包 i=1....100000
![image](https://user-images.githubusercontent.com/12693198/149503969-3a88b2fe-457a-4065-a9bd-7b5653917bd6.png)

**Comment by DrmagicE** [comment] 2022-01-14 11:13
> 但我遇到一个问题是，服务器启动后，有一个客户端连接并push比较大的数据后，ctrl+c终止它，多试几次就卡住
> 旧客户端的连接关闭不了，整个服务器必须要kill -9才能关闭！

I think I misunderstood your problem.  Do you mean the gmqtt broker (not the gmqtt client) will hang on exit(ctrl+c) while serving massive publish messages?

**Comment by DrmagicE** [comment] 2022-01-14 11:15
> 但我遇到一个问题是，服务器启动后，有一个客户端连接并push比较大的数据后，ctrl+c终止它，多试几次就卡住
> 旧客户端的连接关闭不了，整个服务器必须要kill -9才能关闭！

I think I misunderstood your problem.  Do you mean the gmqtt broker (not the gmqtt client) will hang on exit(ctrl+c) while serving massive publish messages?

**Comment by charliexp** [comment] 2022-01-14 13:34
在大量push消息时候，中途把客户端退出，再运行，再推出...
服务端容易卡住，卡在的点如下图：
![image](https://user-images.githubusercontent.com/12693198/149523463-30d766d9-727c-49df-9133-894243a7cb16.png)

正常客户端退出服务端是这样的：（有最后的一行）
![image](https://user-images.githubusercontent.com/12693198/149522647-6924f3c7-3d1f-4edd-a74b-ccb09fbefb85.png)

**Comment by charliexp** [comment] 2022-01-14 13:37
此时（服务端异常时）如果客户端再连接，会出现下图所示：
![image](https://user-images.githubusercontent.com/12693198/149523908-ae5da230-40ca-42b4-b695-d0309e6e52fa.png)
造成客户端连接不了。

**Comment by charliexp** [comment] 2022-01-14 13:38
这时发现服务端不能用ctrl+c结束，必须用kill -9来结束，我不知道描述清楚了没

**Comment by charliexp** [comment] 2022-01-14 14:05
这个要容我慢慢看看，你这个资料太少，我想异常关闭客户端，可能会使数据包截断，会不会socket没有超时而关闭不了，如果客户端发送小量数据，测试没有看到以上问题（应该说不容看到）。

**Closed** 2022-04-16 08:00 UTC
